In [ ]:
import  numpy as np
numbers = np.array([10,20,30,40])
print(numbers*2)


[20 40 60 80]


In [ ]:
a = np.array([10,20,30,40])
print(a)
print(a*2)
print(a+5)

[10 20 30 40]
[20 40 60 80]
[15 25 35 45]


In [8]:
#1D Array
# A 1D array is like a single row.
a= np.array([10,20,30,40])
print(a)


[10 20 30 40]


In [9]:
# 2D Array
# A 2D array is like a table containing rows and columns.
arr = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#3D Array
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.
# These are often used to represent a 3rd order tensor.
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
